version: "3.9"

services:

  postgres:
    image: "postgres:11-alpine"
    environment:
      POSTGRES_DB: mascot
      POSTGRES_USER: mascot-user
      POSTGRES_PASSWORD: "password"
    ports:
      - "5000:5432"

